### ISSUE TITLE
Kirin Ichiban to be removed?

### ISSUE THREAD

**Issue by sithukyaw007** [freedomformyanmar/military-biz-list#13]
Should Kirin Ichiban to be removed from the list?

Ref: 

- https://www.channelnewsasia.com/news/asia/japan-kirin-terminate-myanmar-beer-alliance-after-coup-14117312
- https://www.bbc.com/news/business-55944643

**Comment by freedomformyanmar** [comment]
Kirin Ichiban has renounced their ties with the military yet their products are still available in the market.
Shouldn't be removed as of right now.

**Comment by sithukyaw007** [comment]
Alright thanks
